# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'body.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class body_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 558)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/logo.jpg"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QPushButton{\n"
                                 "    font: 8pt \"楷体\";\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("#frame{\n"
                                 "    background-color: rgb(56, 57, 60);\n"
                                 "    \n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("#frame_2{\n"
                                   "    background-color: rgb(86, 88, 93);\n"
                                   "    \n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setStyleSheet("QPushButton{\n"
                                   "    \n"
                                   "    background-color:qlineargradient(spread:pad,x1:0,y1:0,x2:1, y2:1, stop:0\n"
                                   "rgba(102,133,156,255), stop:1 rgba(117,255,201,255));\n"
                                   "    border-radius:15px;\n"
                                   "    font: 8pt \"幼圆\";\n"
                                   "    color: rgb(255, 255, 255);\n"
                                   "}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(15, 5, 5, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bt_param = QtWidgets.QPushButton(self.frame_9)
        self.bt_param.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_param.setMaximumSize(QtCore.QSize(1000, 1000))
        self.bt_param.setObjectName("bt_param")
        self.horizontalLayout_6.addWidget(self.bt_param, 0, QtCore.Qt.AlignLeft)
        self.bt_version = QtWidgets.QPushButton(self.frame_9)
        self.bt_version.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_version.setMaximumSize(QtCore.QSize(1000, 1000))
        self.bt_version.setObjectName("bt_version")
        self.horizontalLayout_6.addWidget(self.bt_version, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet("QPushButton{\n"
                                   "    border:none;\n"
                                   "}\n"
                                   "QPushButton{\n"
                                   "    padding-bottom:5px;\n"
                                   "}\n"
                                   "")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 40, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bu_max = QtWidgets.QPushButton(self.frame_4)
        self.bu_max.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bu_max.setIcon(icon1)
        self.bu_max.setIconSize(QtCore.QSize(50, 20))
        self.bu_max.setObjectName("bu_max")
        self.horizontalLayout_2.addWidget(self.bu_max)
        self.bu_min = QtWidgets.QPushButton(self.frame_4)
        self.bu_min.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bu_min.setIcon(icon2)
        self.bu_min.setIconSize(QtCore.QSize(50, 20))
        self.bu_min.setObjectName("bu_min")
        self.horizontalLayout_2.addWidget(self.bu_min)
        self.bu_exit = QtWidgets.QPushButton(self.frame_4)
        self.bu_exit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/back.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.bu_exit.setIcon(icon3)
        self.bu_exit.setIconSize(QtCore.QSize(50, 20))
        self.bu_exit.setObjectName("bu_exit")
        self.horizontalLayout_2.addWidget(self.bu_exit)
        self.horizontalLayout_3.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setStyleSheet("QPushButton{\n"
                                   "    background-color: rgb(176, 221, 255);\n"
                                   "    border-radius:15px;\n"
                                   "    font: 12pt \"幼圆\";\n"
                                   "}\n"
                                   "")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setStyleSheet("QPushButton{\n"
                                   "    background-color:qlineargradient(spread:pad,x1:0,y1:0,x2:1, y2:1, stop:0\n"
                                   "rgba(102,133,156,255), stop:1 rgba(117,255,201,255));\n"
                                   "    border-radius:20px;\n"
                                   "    font: 8pt \"幼圆\";\n"
                                   "    color: rgb(255, 255, 255);\n"
                                   "}\n"
                                   "")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bt_openHK = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_openHK.sizePolicy().hasHeightForWidth())
        self.bt_openHK.setSizePolicy(sizePolicy)
        self.bt_openHK.setMinimumSize(QtCore.QSize(80, 60))
        self.bt_openHK.setObjectName("bt_openHK")
        self.verticalLayout_4.addWidget(self.bt_openHK)
        self.bt_openUSB = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_openUSB.sizePolicy().hasHeightForWidth())
        self.bt_openUSB.setSizePolicy(sizePolicy)
        self.bt_openUSB.setMinimumSize(QtCore.QSize(80, 60))
        self.bt_openUSB.setObjectName("bt_openUSB")
        self.verticalLayout_4.addWidget(self.bt_openUSB)
        self.bt_close = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_close.sizePolicy().hasHeightForWidth())
        self.bt_close.setSizePolicy(sizePolicy)
        self.bt_close.setMinimumSize(QtCore.QSize(80, 60))
        self.bt_close.setObjectName("bt_close")
        self.verticalLayout_4.addWidget(self.bt_close)
        self.bt_close_usb = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_close_usb.sizePolicy().hasHeightForWidth())
        self.bt_close_usb.setSizePolicy(sizePolicy)
        self.bt_close_usb.setMinimumSize(QtCore.QSize(80, 60))
        self.bt_close_usb.setObjectName("bt_close_usb")
        self.verticalLayout_4.addWidget(self.bt_close_usb)
        self.verticalLayout_3.addWidget(self.frame_8, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.la_class = QtWidgets.QLabel(self.frame_7)
        self.la_class.setStyleSheet("color: rgb(220, 220, 220);\n"
                                    "font: 18pt \"幼圆\";")
        self.la_class.setObjectName("la_class")
        self.verticalLayout_2.addWidget(self.la_class, 0, QtCore.Qt.AlignHCenter)
        self.la_img = QtWidgets.QLabel(self.frame_7)
        self.la_img.setText("")
        self.la_img.setObjectName("la_img")
        self.verticalLayout_2.addWidget(self.la_img)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 9)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 8)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 12)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionxiugai = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.actionxiugai.setFont(font)
        self.actionxiugai.setObjectName("actionxiugai")
        self.actiondaixao = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.actiondaixao.setFont(font)
        self.actiondaixao.setObjectName("actiondaixao")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/back.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionversion = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.actionversion.setFont(font)
        self.actionversion.setObjectName("actionversion")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setIcon(icon4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.actionExit_2.setFont(font)
        self.actionExit_2.setObjectName("actionExit_2")

        self.retranslateUi(MainWindow)
        self.bu_exit.clicked.connect(MainWindow.close)  # type: ignore
        self.bu_min.clicked.connect(MainWindow.showMinimized)  # type: ignore
        self.bu_max.clicked.connect(MainWindow.showMaximized)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智屏微翻肛鉴别系统"))
        self.bt_param.setText(_translate("MainWindow", "修改参数"))
        self.bt_version.setText(_translate("MainWindow", "关于"))
        self.bt_openHK.setText(_translate("MainWindow", "打开工业摄像头"))
        self.bt_openUSB.setText(_translate("MainWindow", "打开USB摄像头"))
        self.bt_close.setText(_translate("MainWindow", "关闭摄像头"))
        self.bt_close_usb.setText(_translate("MainWindow", "打开文件图片"))
        self.la_class.setText(_translate("MainWindow", "类别: **    概率: **"))
        self.actionxiugai.setText(_translate("MainWindow", "修改参数"))
        self.actiondaixao.setText(_translate("MainWindow", "镜头大小"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionExit.setToolTip(_translate("MainWindow", "退出"))
        self.actionversion.setText(_translate("MainWindow", "版本号"))
        self.actionversion.setToolTip(_translate("MainWindow", "版本号"))
        self.actionExit_2.setText(_translate("MainWindow", "退出"))
        self.actionExit_2.setToolTip(_translate("MainWindow", "退出"))



